# Generated by Django 5.2 on 2026-04-01 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInterno',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('AUDITOR_LIDER', 'Auditor Líder'), ('AUDITOR', 'Auditor'), ('EJECUTIVO', 'Ejecutivo Comercial')], default='AUDITOR', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10)),
                ('mfa_habilitado', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, help_text='Clave secreta TOTP (base32)', max_length=64)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=128)),
                ('reset_token_expira', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario Interno',
                'verbose_name_plural': 'Usuarios Internos',
                'db_table': 'usuarios_internos',
            },
        ),
    ]
