import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='SedeCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('nombre', models.CharField(max_length=150)),
                ('es_principal', models.BooleanField(default=False)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_sede', models.EmailField(blank=True)),
                ('num_empleados', models.PositiveIntegerField(blank=True, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=200)),
                ('responsable_cargo', models.CharField(blank=True, max_length=100)),
                ('responsable_email', models.EmailField(blank=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sedes',
                    to='clientes.cliente',
                )),
            ],
            options={'db_table': 'sedes_cliente', 'ordering': ['-es_principal', 'nombre']},
        ),


        migrations.AddField(model_name='cliente', name='tipo_persona',
            field=models.CharField(
                choices=[('JURIDICA', 'Persona Jurídica'), ('NATURAL', 'Persona Natural')],
                default='JURIDICA', max_length=10)),
        migrations.AddField(model_name='cliente', name='digito_verificacion',
            field=models.CharField(blank=True, max_length=2)),
        migrations.AddField(model_name='cliente', name='matricula_mercantil',
            field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='cliente', name='fecha_constitucion',
            field=models.DateField(null=True, blank=True)),
        migrations.AddField(model_name='cliente', name='duracion_empresa',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='cliente', name='objeto_social',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='cliente', name='codigo_ciiu',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='cliente', name='regimen_tributario',
            field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name='cliente', name='responsable_iva',
            field=models.BooleanField(default=True)),
        migrations.AddField(model_name='cliente', name='rep_legal_nombre',
            field=models.CharField(blank=True, max_length=200)),
        migrations.AddField(model_name='cliente', name='rep_legal_documento',
            field=models.CharField(blank=True, max_length=30)),
        migrations.AddField(model_name='cliente', name='rep_legal_tipo_doc',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='cliente', name='rep_legal_cargo',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='cliente', name='rep_legal_email',
            field=models.EmailField(blank=True)),
        migrations.AddField(model_name='cliente', name='rep_legal_telefono',
            field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name='cliente', name='departamento',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='cliente', name='direccion_principal',
            field=models.CharField(blank=True, max_length=300)),
        migrations.AddField(model_name='cliente', name='codigo_postal',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='cliente', name='sedes_adicionales',
            field=models.JSONField(default=list, blank=True)),
        migrations.AddField(model_name='cliente', name='telefono_alt',
            field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name='cliente', name='linkedin',
            field=models.URLField(blank=True)),
        migrations.AddField(model_name='cliente', name='subsector',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='cliente', name='tamano',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='cliente', name='num_empleados',
            field=models.PositiveIntegerField(null=True, blank=True)),
        migrations.AddField(model_name='cliente', name='ingresos_anuales',
            field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='cliente', name='tipos_auditoria_solicitados',
            field=models.JSONField(default=list, blank=True)),
        migrations.AddField(model_name='cliente', name='alcance_descripcion',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='cliente', name='normas_interes',
            field=models.JSONField(default=list, blank=True)),
        migrations.AddField(model_name='cliente', name='tiene_certificacion_previa',
            field=models.BooleanField(default=False)),
        migrations.AddField(model_name='cliente', name='certificacion_previa_detalle',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='cliente', name='motivo_auditoria',
            field=models.CharField(blank=True, max_length=25)),
        migrations.AddField(model_name='cliente', name='declaracion_necesidad',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='cliente', name='urgencia',
            field=models.CharField(blank=True, default='MEDIA', max_length=10)),
        migrations.AddField(model_name='cliente', name='fecha_limite_deseada',
            field=models.DateField(null=True, blank=True)),
        migrations.AddField(model_name='cliente', name='caracterizacion_completada',
            field=models.BooleanField(default=False)),
        migrations.AddField(model_name='cliente', name='fecha_caracterizacion',
            field=models.DateTimeField(null=True, blank=True)),
        migrations.AddField(model_name='cliente', name='asesor_responsable',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clientes_asesorados',
                to=settings.AUTH_USER_MODEL,
            )),
        migrations.AlterField(model_name='cliente', name='estado',
            field=models.CharField(
                choices=[
                    ('PROSPECTO', 'Prospecto'), ('EN_EVALUACION', 'En evaluación'),
                    ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'),
                ],
                default='PROSPECTO', max_length=15)),
        migrations.AlterField(model_name='cliente', name='sector',
            field=models.CharField(
                max_length=20, default='OTRO',
                choices=[
                    ('TECNOLOGIA', 'Tecnología'), ('SALUD', 'Salud'),
                    ('FINANCIERO', 'Financiero / Fintech'),
                    ('MANUFACTURA', 'Manufactura / Industrial'),
                    ('SERVICIOS', 'Servicios'), ('GOBIERNO', 'Gobierno / Sector Público'),
                    ('EDUCACION', 'Educación'), ('ENERGIA', 'Energía y Recursos'),
                    ('TRANSPORTE', 'Transporte y Logística'),
                    ('CONSTRUCCION', 'Construcción e Inmobiliario'),
                    ('COMERCIO', 'Comercio y Retail'), ('AGROPECUARIO', 'Agropecuario'),
                    ('TELECOMUNICACIONES', 'Telecomunicaciones'),
                    ('SEGUROS', 'Seguros'), ('OTRO', 'Otro'),
                ])),


        migrations.AddField(model_name='contactocliente', name='tipo',
            field=models.CharField(
                default='OPERATIVO', max_length=15,
                choices=[
                    ('OPERATIVO', 'Contacto Operativo'), ('GERENCIAL', 'Gerencial'),
                    ('TECNICO', 'Técnico'), ('ADMINISTRATIVO', 'Administrativo'),
                    ('JURIDICO', 'Jurídico'), ('FINANCIERO', 'Financiero'),
                ])),
        migrations.AddField(model_name='contactocliente', name='departamento',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='contactocliente', name='telefono_ext',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='contactocliente', name='celular',
            field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name='contactocliente', name='recibe_informes',
            field=models.BooleanField(default=True)),
        migrations.AddField(model_name='contactocliente', name='recibe_notificaciones',
            field=models.BooleanField(default=True)),
        migrations.AddField(model_name='contactocliente', name='notas',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='contactocliente', name='sede',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contactos',
                to='clientes.sedecliente',
            )),


        migrations.CreateModel(
            name='AccesoTemporalCaracterizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email_destino', models.EmailField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('ip_uso', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='accesos_temporales',
                    to='clientes.cliente',
                )),
                ('contacto', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='clientes.contactocliente',
                )),
                ('creado_por', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='accesos_generados',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={'db_table': 'accesos_temporales_caracterizacion'},
        ),
    ]
