# Generated by Django 5.2 on 2026-04-01 13:51

import apps.certificaciones.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('expedientes', '0001_initial'),
        ('tipos_auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('codigo_verificacion', models.CharField(editable=False, max_length=64, unique=True)),
                ('tipo_emision', models.CharField(choices=[('PROPIA', 'Propia'), ('EXTERNA', 'Externa')], default='PROPIA', max_length=8)),
                ('ente_certificador', models.CharField(blank=True, max_length=200)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDA', 'Vencida'), ('REVOCADA', 'Revocada')], default='VIGENTE', max_length=12)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to=apps.certificaciones.models.cert_upload_path)),
                ('hash_documento', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificaciones', to='clientes.cliente')),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificacion', to='expedientes.expediente')),
                ('tipo_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_auditoria.tipoauditoria')),
            ],
            options={
                'db_table': 'certificaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='AlertaCertificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('90_DIAS', '90 días'), ('60_DIAS', '60 días'), ('30_DIAS', '30 días'), ('VENCIDA', 'Vencida')], max_length=10)),
                ('fecha_programada', models.DateField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push'), ('SISTEMA', 'Sistema'), ('TODOS', 'Todos')], default='TODOS', max_length=8)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='certificaciones.certificacion')),
            ],
            options={
                'db_table': 'alertas_certificacion',
            },
        ),
    ]
