# Generated by Django 5.2 on 2026-04-01 13:51

import apps.ejecucion.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        ('tipos_auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('HALLAZGO', 'Hallazgo'), ('OBSERVACION', 'Observación'), ('NO_CONFORMIDAD', 'No Conformidad'), ('OPORTUNIDAD', 'Oportunidad de Mejora')], default='HALLAZGO', max_length=20)),
                ('nivel_criticidad', models.CharField(choices=[('CRITICO', 'Crítico'), ('MAYOR', 'Mayor'), ('MENOR', 'Menor'), ('INFORMATIVO', 'Informativo')], default='MENOR', max_length=15)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En Revisión'), ('CERRADO', 'Cerrado'), ('ACEPTADO_CON_RIESGO', 'Aceptado con Riesgo')], default='ABIERTO', max_length=20)),
                ('fecha_limite_cierre', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_asignados', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='expedientes.expediente')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hallazgos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=apps.ejecucion.models.evidencia_upload_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('tamanio_bytes', models.BigIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='expedientes.expediente')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hallazgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='ejecucion.hallazgo')),
            ],
            options={
                'db_table': 'evidencias',
            },
        ),
        migrations.CreateModel(
            name='ChecklistEjecucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='expedientes.expediente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_auditoria.checklistitem')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejecucion.evidencia')),
            ],
            options={
                'db_table': 'checklist_ejecucion',
                'unique_together': {('expediente', 'item')},
            },
        ),
    ]
